config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :profiles
  resources :posts
  root "users#new"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validate :any_present?

  def any_present?
    if %w(texts image).all?{|attr| self[attr].blank?}
      errors.add :base, "please post at least one field"
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :full_name, presence: true, length: { maximum: 100 }
  validates :username, presence:true, length: { maximum: 100 }
  validates :email, presence:true, length: { maximum: 100 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }
  has_many :posts
  has_many :profiles
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def index
    @profiles = Profile.all
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to contacts_path, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end
      def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite = Favorite.all
    @profiles = Profile.all
  end
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_url
  end
    
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @profiles = Profile.all
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id 

    respond_to do |format|
      if @post.save
        #ContactMailer.contact_mail(@post).deliver
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id 
    render :new if @post.invalid?
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:texts, :image, :image_cache, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = current_user.profiles
  end

  def show
  end

  def new
    @profile = Profile.new
  end


  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profiles_path }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    render :new if @profile.invalid?
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    def set_profile
      @profile = Profile.find_by(params[:user_id])
    end

    def profile_params
      params.require(:profile).permit(:image, :image_cache, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path()
    else
      flash.now[:danger] = 'Login failed'
      render 'new'
    end
  end

  def destroy 
    session.delete (:user_id )
    redirect_to new_session_path
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
      else
        render 'new'
      end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/favorites/index.html.erb
<div class="super">
  <% if logged_in? %>
    <% check = 0, profile_pic='1', id=nil, nam=nil %>
    <% @profiles.each do |profile| %>
      <% if current_user.id == profile.user_id %>
        <% check = 1%>
        <%nam= profile.user.full_name%>
        <%profile_pic = profile.image.url %>  
      <% end %>
    <% end %>
    <% if check==1 %>
      <p>
        <%= image_tag profile_pic, size:"150x150",class:"rounded-circle" unless profile_pic.blank? %>
        <h2><%= nam%></h2>
      </p>
    <% else %>
      <p><%=image_tag "user.png", size:"150x150",class:"rounded-circle" %></p>
      <%= nam%>
    <% end %>
  <% end %>
  <h5>My favorite posts</h5>
  <% @favorite.each do |fav| %>
    <%if current_user.id == fav.user.id%> <div>
    <div class="p-3 mb-2 bg-white text-dark border">
    <p><strong><%= fav.post.user.username%></strong></p><br>
    <small><%= fav.post.texts%></small>
    <div><%= image_tag fav.post.image.url,alt:"No pic" unless fav.post.image.url.blank? %></div>
    </div>
    <%end%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body class="body">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="super">

      <% if logged_in? %>
      <div class="p-3 mb-2 bg-white text-dark border">
      <h1 class="text-center">Instagram</h1>
        <%= link_to "Home", posts_path %>
        <%= link_to "Profile", profiles_path(current_user.id) %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        </ul>
      </div>
    </div>
  

    <% end %>

    <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="super bg-white text-dark border">
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :say_something %>
    <%= form.text_area :texts, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :Upload_image %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit "Publish", class:"btn btn-success" %>
  </div>
  <%= link_to 'Back', posts_path %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="super">

<p id="notice"><%= notice %></p>

<% if logged_in? %>
  <% check = 0, profile_pic='1', id=nil, nam=nil %>
  <% @profiles.each do |profile| %>
    <% if current_user.id == profile.user_id %>
      <% check = 1%>
      <%nam= profile.user.full_name%>
      <%profile_pic = profile.image.url %>
    
    <% end %>
  <% end %>
  <% if check==1 %>
    <p><%= image_tag profile_pic, size:"150x150",class:"rounded-circle" unless profile_pic.blank? %>
    <h2><%= nam%></h2>
    </p>
  <% else %>
    <p><%=image_tag "user.png", size:"150x150",class:"rounded-circle" %></p>
    <%= nam%>
  <% end %>
<% end %>

    <button class="btn btn-info">
      <a>
        <%= link_to 'New Post', new_post_path %>
      </a>
    </button>
    <% @posts.each do |post| %>
      <div class="p-3 mb-2 bg-white text-dark border">
      <p>
      <strong><%= post.user.username %></strong>
      </p>
      <p>
        <% if post.texts %>
          <%= post.texts %>
        <% end %>
      </p>
      <p>
        <% if post.image.url %>
          <%= image_tag post.image.url %>      
        <% end %>
      </p>
      <p>
      <a><%= link_to 'Show', post %></a>
      <% if logged_in? %>
        <% if current_user.id == post.user_id %>
          <a><%= link_to 'Edit', edit_post_path(post) %></a>
          <a><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></a>
        <% end %>
      <% end %>
      </p>
      </div>
    <% end %>

</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="super">
  <p id="notice"><%= notice %></p>
  <div class="p-3 mb-2 bg-white text-dark border">
    <p>
      <strong><%= @post.user.username %><strong>
    </p>

    <p> 
      <% if @post.texts %>
        <small><%= @post.texts %></small>
      <% end %>
    </p>

    <p>
      <% if @post.image.url %>
        <%= image_tag @post.image.url %>
      <% end %>
    </p>
    <%= link_to 'Back', posts_path %>
    <% if logged_in? %>
      <% if current_user.id == @post.user_id %>
        <%= link_to 'Edit', edit_post_path(@post) %>
    <% end %>
    <% unless @post.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'Unlike', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'Like', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :upload_image %>
    <%= image_tag(@profile.image.url) if @profile.image && @profile.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="form-group">
  <%= form.submit "change profile", class:" btn btn-success" %>
  </div>
    
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="super">
<p id="notice"><%= notice %></p>

<% if logged_in? %>
  <% check = 0, profile_pic='1', id=nil, nam=nil %>
  <% @profiles.each do |profile| %>
    <% if current_user.id == profile.user_id %>
      <% check = 1%>
      <%nam= profile.user.full_name%>
      <%profile_pic = profile.image.url %>
    
    <% end %>
  <% end %>
  <% if check==1 %>
    <p>
      <%= image_tag profile_pic, size:"150x150",class:"rounded-circle" unless profile_pic.blank? %>
    
    <button class="btn btn-info">
      <%= link_to 'change profile', new_profile_path %>
    </button>
    </p>

    
    
    <p><h2><%= nam%></h2>
    <button class="btn btn-warning border">
      <%= link_to 'view favorites', favorites_path %>
    </button>
    </p>  
  <% else %>
    <p>
    <%=image_tag "user.png", size:"150x150",class:"rounded-circle" %>
    <button class="btn btn-info">
      <%= link_to 'change profile', new_profile_path %>
    </button>
    </p>

    <h2><%= nam%></h2>
    <button class="btn btn-warning border">
      <%= link_to 'view favorites', favorites_path %>
    </button>
  <% end %>
  
<% end %>

<h6>Profile pictures</h6>


    <% @profiles.each do |profile| %>
      <div class="p-3 mb-2 bg-white text-dark border">
      <%= image_tag profile.image.url %>
      </div>
    <% end %>
</div>

app/views/profiles/new.html.erb
<div class="super">
<div class="main-form">
<%= render 'form', profile: @profile %>
<button class="btn btn-info"><%= link_to 'Back', profiles_path %></button>
</div>

</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @profile.user.username %></strong>
</p>
<p>
  <%= image_tag @profile.image.url %>
</p>



<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="main-form border">
<h1 class="text-center">Instagram</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
  <%= f.text_field :full_name, placeholder:"full name", class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.text_field :username, placeholder:"username", class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.email_field :email, placeholder:"email", class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.password_field :password, placeholder:"password", class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.password_field :password_confirmation, placeholder:"confirm password", class:"form-control" %>
  </div>

  <div class="form-group ">
  <%= f.submit "Sign up", class:"form-control btn btn-info" %>
  </div>
<% end %>
</div>
<div class="main-form border">
  <label>Have an account? <a><%= link_to "Log in", new_session_path %><a></label>
</div>

app/views/users/show.html.erb
<h2>Welcome</h2>
<h1><%= @user.full_name %></h1> 
<h2>your account has been created successfully</h2>

<h5>Click here to login </h5>
<button class="btn btn-info"><%= link_to "Log in", new_session_path %></button>